import TrainerWorkspace from "../trainer/TrainerWorkspace";

export default function AdminWorkoutsNextWorkspace({
  appVersion,
  trainerName,
  trainerAvatar,
  clients,
  selectedClient,
  workouts,
  exerciseLibrary,
  programTemplates,
  selectedProgramId,
  onSelectProgram,
  onAssignProgram,
  onSaveWorkoutSchedule,
  onOpenProgramManager,
  activeWorkoutTab,
  onWorkoutTabChange,
  programStatus,
  onUpdateWorkout,
  onUpdateExercise,
  onUpdateLibraryExercise,
  onRemoveLibraryExercise,
  onCreateLibraryExercise,
  onUpdateExerciseSet,
  onAddExerciseSet,
  onRemoveExerciseSet,
  onAddExercise,
  onRemoveExercise,
  onDuplicateExercise,
  onMoveExercise,
  onUploadExerciseVideo,
  onUploadLibraryExerciseVideo,
  exerciseVideoUploadingId,
  onAddDay,
  onDuplicateDay,
  onRemoveDay,
  onSaveWorkouts,
  onCreateClient,
  createClientState,
  onNavigate,
  mode,
  activeSection,
  embedded = false
}) {
  return (
    <TrainerWorkspace
      appVersion={appVersion}
      embedded={embedded}
      mode={mode}
      activeSection={activeSection}
      onNavigate={onNavigate}
      trainerName={trainerName}
      trainerAvatar={trainerAvatar}
      clients={clients}
      selectedClient={selectedClient || null}
      workouts={workouts}
      exerciseLibrary={exerciseLibrary}
      programTemplates={programTemplates}
      selectedProgramId={selectedProgramId}
      onSelectProgram={onSelectProgram}
      onAssignProgram={onAssignProgram}
      onSaveWorkoutSchedule={onSaveWorkoutSchedule}
      onOpenProgramManager={onOpenProgramManager}
      activeWorkoutTab={activeWorkoutTab}
      onWorkoutTabChange={onWorkoutTabChange}
      programStatus={programStatus}
      onUpdateWorkout={onUpdateWorkout}
      onUpdateExercise={onUpdateExercise}
      onUpdateLibraryExercise={onUpdateLibraryExercise}
      onRemoveLibraryExercise={onRemoveLibraryExercise}
      onCreateLibraryExercise={onCreateLibraryExercise}
      onUpdateExerciseSet={onUpdateExerciseSet}
      onAddExerciseSet={onAddExerciseSet}
      onRemoveExerciseSet={onRemoveExerciseSet}
      onAddExercise={onAddExercise}
      onRemoveExercise={onRemoveExercise}
      onDuplicateExercise={onDuplicateExercise}
      onMoveExercise={onMoveExercise}
      onUploadExerciseVideo={onUploadExerciseVideo}
      onUploadLibraryExerciseVideo={onUploadLibraryExerciseVideo}
      exerciseVideoUploadingId={exerciseVideoUploadingId}
      onAddDay={onAddDay}
      onDuplicateDay={onDuplicateDay}
      onRemoveDay={onRemoveDay}
      onSaveWorkouts={onSaveWorkouts}
      onCreateClient={onCreateClient}
      createClientState={createClientState}
    />
  );
}
