export function createAppRouterProps({
  page,
  appVersion,
  workoutModeRemember,
  canUseAdminFeatures,
  renderNutritionPage,
  workoutListProps,
  basicWorkoutQuiz,
  goBackToMain,
  openBasicWorkoutQuiz,
  openSavedBasicWorkoutsOrQuiz,
  openIndividualWorkouts,
  saveWorkoutModePreference,
  workoutModePreference,
  setWorkoutModeRemember,
  setPage,
  applyBasicWorkoutPlan,
  setBasicWorkoutQuiz,
  openAdminProgramsOverview,
  history,
  historyLoading,
  openHistoryKey,
  historySwipeId,
  historyDeletingId,
  historyDeleteCandidate,
  loadHistory,
  handleHistoryTouchStart,
  handleHistoryTouchEnd,
  requestDeleteOwnHistoryWorkout,
  setOpenHistoryKey,
  closeHistoryDeleteConfirm,
  confirmDeleteOwnHistoryWorkout,
  aiNutritionProfile,
  aiNutritionProfileDraft,
  profileMeasurements,
  profileMeasurementWizardStep,
  profileMeasurementDraft,
  profileMeasurementStatus,
  profileMeasurementSaving,
  setProfileMeasurementDraft,
  setProfileMeasurementStatus,
  setProfileMeasurementWizardStep,
  setProfileMeasurementOpen,
  setProfileActiveTab,
  profileMeasurementReturnTab,
  saveProfileMeasurement,
  selectedAiFeatureId,
  setSelectedAiFeatureId,
  aiNutritionSavedPlan,
  setAiNutritionProfileDraft,
  saveAiNutritionPlan,
  resetAiNutritionPlan,
  nutritionDateKey,
  aiNutritionAdaptedToday,
  setAiNutritionAdaptedToday,
  plan,
  nutrition,
  user,
  getCompletedWorkoutSet,
  isWorkoutCompletedByHistory,
  workoutPlanRouteHandlers
}) {
  return {
    page,
    appVersion,
    workoutModeRemember,
    canUseAdminFeatures,
    renderNutritionPage,
    workoutListProps,
    basicWorkoutQuiz,
    workoutModePreference,
    onBackToMain: goBackToMain,
    onOpenBasicWorkoutQuiz: openBasicWorkoutQuiz,
    onOpenSavedBasicWorkoutsOrQuiz: openSavedBasicWorkoutsOrQuiz,
    onOpenIndividualWorkouts: openIndividualWorkouts,
    onSetWorkoutModeRemember: (remember) => {
      if (workoutModePreference?.mode) {
        saveWorkoutModePreference(workoutModePreference.mode, remember);
        return;
      }

      setWorkoutModeRemember(remember);
    },
    onSetPage: setPage,
    onApplyBasicWorkoutPlan: applyBasicWorkoutPlan,
    onBasicWorkoutQuizChange: setBasicWorkoutQuiz,
    openAdminProgramsOverview,
    history,
    historyLoading,
    openHistoryKey,
    historySwipeId,
    historyDeletingId,
    historyDeleteCandidate,
    loadHistory,
    handleHistoryTouchStart,
    handleHistoryTouchEnd,
    requestDeleteOwnHistoryWorkout,
    setOpenHistoryKey,
    closeHistoryDeleteConfirm,
    confirmDeleteOwnHistoryWorkout,
    aiNutritionProfile,
    aiNutritionProfileDraft,
    profileMeasurements,
    profileMeasurementWizardStep,
    profileMeasurementDraft,
    profileMeasurementStatus,
    profileMeasurementSaving,
    setProfileMeasurementDraft,
    setProfileMeasurementStatus,
    setProfileMeasurementWizardStep,
    setProfileMeasurementOpen,
    setProfileActiveTab,
    profileMeasurementReturnTab,
    saveProfileMeasurement,
    selectedAiFeatureId,
    setSelectedAiFeatureId,
    aiNutritionSavedPlan,
    setAiNutritionProfileDraft,
    saveAiNutritionPlan,
    resetAiNutritionPlan,
    nutritionDateKey,
    aiNutritionAdaptedToday,
    setAiNutritionAdaptedToday,
    plan,
    nutrition,
    user,
    getCompletedWorkoutSet,
    isWorkoutCompletedByHistory,
    workoutPlanRouteHandlers
  };
}
