export const loadAdminPanelHub = () => import("../components/admin/AdminPanelHub");
export const loadAdminBaseLibrary = () => import("../components/admin/AdminBaseLibrary");
export const loadAiCoachPage = () => import("../features/client/ai/AiCoachPage");
export const loadBasicWorkoutQuizPage = () => import("../features/client/workouts/BasicWorkoutQuizPage");
export const loadMeasurementWizardPage = () => import("../features/client/measurements/MeasurementWizardPage");
export const loadWorkoutHistoryPage = () => import("../features/client/workouts/WorkoutHistoryPage");
export const loadWorkoutListPage = () => import("../features/client/workouts/WorkoutListPage");
export const loadWorkoutModePage = () => import("../features/client/workouts/WorkoutModePage");
export const loadWorkoutPlanPage = () => import("../features/client/workouts/WorkoutPlanPage");
